/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Carro;
import model.dao.CarroDAO;
import model.bean.Locadora;
import model.dao.LocadoraDAO;
import model.bean.Pessoa;
import model.bean.Seguro;
import model.dao.PessoaDAO;
import model.dao.SeguroDAO;
/**
 *
 * @author Rafael
 */
public class Alugar extends javax.swing.JFrame {
    public Alugar() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTCarros.getModel();
        jTCarros.setRowSorter(new TableRowSorter(modelo));

        readJTable();
        
       
        
        PessoaDAO dao = new PessoaDAO();
        
        for(Pessoa p: dao.read()){
            jcboxCliente.addItem(p);
        
        }
        
        SeguroDAO dao2 = new SeguroDAO();
        
        for(Seguro p: dao2.read()){
            jcboxSeguro.addItem(p);
        
        }
        
        
    }

    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTCarros.getModel();
        modelo.setNumRows(0);
        CarroDAO pdao = new CarroDAO();

        for (Carro c : pdao.read()) {

            modelo.addRow(new Object[]{
                c.getId(),
                c.getModelo(),
                c.getAno(),
                c.getReservado(),
                c.getLocadoraID(),
                c.getLocadoraNome(),
                c.getPessoaID(),
                c.getPessoaNome(),
                c.getSeguroID()
                    
                    
            });
        }

    }
   
     public void readJTableForDesc2(String desc) {
        
        DefaultTableModel reservado = (DefaultTableModel) jTCarros.getModel();
        reservado.setNumRows(0);
        CarroDAO pdao = new CarroDAO();

        for (Carro c : pdao.readForDesc2(desc)) {

            reservado.addRow(new Object[]{
                c.getId(),
                c.getModelo(),
                c.getAno(),
                c.getReservado(),
                c.getLocadoraID(),
                c.getPessoaID(),
                c.getSeguroID()
            });

        }

    }
    /**
     * Creates new form Alugar
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jbtVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCarros = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jbtAttCliente = new javax.swing.JButton();
        jcboxCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbtBuscaReservado = new javax.swing.JButton();
        jcboxSeguro = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonNao = new javax.swing.JRadioButton();
        jRadioButtonSim = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtVoltar.setText("<< Voltar");
        jbtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVoltarActionPerformed(evt);
            }
        });

        jTCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Modelo", "Ano", "Reservado", "ID Locadora", "Nome Locad.", "ID Pessoa", "Nome Pessoa", "Seguro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCarrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCarros);

        jLabel4.setText("Carro");

        txtModelo.setEditable(false);

        jbtAttCliente.setText("Confirmar");
        jbtAttCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAttClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Alugar este Carro para o Cliente:");

        jbtBuscaReservado.setText("Buscar");
        jbtBuscaReservado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscaReservadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pesquisar por:");

        buttonGroup1.add(jRadioButtonNao);
        jRadioButtonNao.setText("Carros Disponívies");

        buttonGroup1.add(jRadioButtonSim);
        jRadioButtonSim.setText("Carros Reservados");

        jLabel2.setText("Selecionar o Seguro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtAttCliente)
                                .addGap(499, 499, 499)
                                .addComponent(jRadioButtonSim))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonNao)))
                        .addGap(18, 18, 18)
                        .addComponent(jbtBuscaReservado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jcboxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcboxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jbtVoltar))
                        .addContainerGap(445, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtVoltar)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcboxSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jbtBuscaReservado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonNao)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtAttCliente)
                            .addComponent(jRadioButtonSim))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVoltarActionPerformed
        // TODO add your handling code here:
        
        this.dispose(); 
        new Index().setVisible(true); 
    }//GEN-LAST:event_jbtVoltarActionPerformed

    private void jbtAttClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAttClienteActionPerformed
        // TODO add your handling code here:
        
        Seguro seguro = (Seguro) jcboxSeguro.getSelectedItem();
        int aux2 = seguro.getId();
        
        
        Pessoa pessoa = (Pessoa) jcboxCliente.getSelectedItem();
        int aux = pessoa.getId();
        
        if (jTCarros.getSelectedRow() != -1) {

            Carro c = new Carro();
            CarroDAO dao = new CarroDAO();     
            
            c.setPessoaID(aux);    
            c.setSeguroID(aux2); 
            c.setId((int) jTCarros.getValueAt(jTCarros.getSelectedRow(), 0));        
            
            dao.update2(c);

            txtModelo.setText("");          
     
            readJTable();

        }



    }//GEN-LAST:event_jbtAttClienteActionPerformed

    private void jbtBuscaReservadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscaReservadoActionPerformed
        // TODO add your handling code here:
        
        
        if(jRadioButtonNao.isSelected()){
            readJTableForDesc2("Não");
        }else if(jRadioButtonSim.isSelected()){
            readJTableForDesc2("Sim");
        }
        
//        readJTableForDesc2(txtBuscaRes.getText());
    }//GEN-LAST:event_jbtBuscaReservadoActionPerformed

    private void jTCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCarrosMouseClicked
        // TODO add your handling code here:

        if (jTCarros.getSelectedRow() != -1) {

            txtModelo.setText(jTCarros.getValueAt(jTCarros.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_jTCarrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonNao;
    private javax.swing.JRadioButton jRadioButtonSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCarros;
    private javax.swing.JButton jbtAttCliente;
    private javax.swing.JButton jbtBuscaReservado;
    private javax.swing.JButton jbtVoltar;
    private javax.swing.JComboBox<Object> jcboxCliente;
    private javax.swing.JComboBox<Object> jcboxSeguro;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
